### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by okj203** [jacktfliu/HotelBnB-Clone-Project-#2]
- [x] Reviews table needs listing_id as a foreign key
- [x] The Booking table needs a column for number of guests
- [x] Adding a num_guests column to the bookings table would also require a num_guest info in the sample state
- [x] The listing table needs address data (longitude and latitude) for Google Maps API, rather than just a location column.
- [x] In the sample state, users’ password digest and session token should not be included. The state should have all the information curated so that sensitive information won’t be presented on the users’ end.
- [x] In the sample state, the reviews entity is missing rating and the reviews table is missing listing_id column.
- [x] In the sample state, the bookings entity has user_id AND `guess_id`, but the bookings table only has guest_id. Choose either the word `user’ or `guest`.
- [x] The frontend routes page in wiki needs more info. Please refer to [this link to a sample frontend routes page.](https://github.com/appacademy/2021-04-19-NYC-Lecture-Notes/wiki/Front-End-Routes-&-Components)

**Comment by jacktfliu** [comment]
Completed checklist.

**Comment by okj203** [comment]
Good job!
